### ISSUE TITLE
Crop image method is not working as expected.

### ISSUE THREAD

**Issue by NagarjunaReddy** [appcelerator-modules/ti.imagefactory#17]
Hi Team,

My requirement is to take a image using camera and i will pass dimensions to image factory module using imageAsCropped method. So in return module has to provide me the image cropped with the dimensions specified. But the image cropped by this module is blurred and zoomed to fit the dimensions.

Thanks
Nag

**Comment by a-axton** [comment]
I was having issues with this as well. What worked for me was setting the x and y option instead of using the defaults and make sure that neither the width or height the same as the original (subtract 1 if it's the same). You also need to count for the pixel density of the images in the crop dimensions which you can get with Ti.Platform.displayCaps.logicalDensityFactor. What worked for me (was changing image ratio from 4:3 to 16:9):

    image = ImageFactory.imageAsCropped(image, {
        x: 0,
        y: 0,
        width: ((image.height*density)/1.777778)-1,
        height: (image.height*density)-1
      });

**Comment by designbymind** [comment]
Hi @a-axton,

Thanks for the above explanation & example code!

I'm still having an issue getting the imageAsCropped method to output my desired result. Since you've been able to figure out how to return what you needed from the module, I figured I'd reach out & ask for a little help.

My current result outputs a similar result to @NagarjunaReddy's, being zoomed, off center, and/or stretched/compacted...

**Here's what I'm looking to do:**

1. Take a photo with the camera (fullscreen portrait device height & device width)
2. Crop the returned photo (e.media) to be square (width = device width & height = device width)
3. Populate ImageView with cropped photo from the actions above

**Here's an image to give you a visual:**
- The camera being fullscreen but the returned (and cropped) photo being centered and square
![image](https://cloud.githubusercontent.com/assets/874832/11889787/bf197f2e-a501-11e5-8b42-5755a80d87de.jpg)


Let me know if you need more info & any help is much appreciated!

· Jason

**Comment by hansemannn** [comment]
@designbymind Is this resolved by now? I would suggest to use the center points and crop it from there using the specified width and height. That worked for me in the past. Thx!

**Comment by designbymind** [comment]
Hey @hansemannn - it's been awhile since I tried using the imageFactory cropping method as I'd found an alternative solution at the time. I even tried using the method you recommended above with no success. However, since having an additional (commonJS) module for cropping is unnecessary overhead if the built-in cropping methods of imageFactory work as expected, I'd be happy to test that out. I'm currently working with the camera for a new app & as soon as I get to that part of the development stage, I'll report back with my findings. Thanks man!
